### PR TITLE
Xml branch

### PR DESCRIPTION
**Pull request by DasGabelhauser**
TP008 - Create Presentation Object

User Stories Complete: n/a
Authors: Eric Walker and Daniel Bishop

### CODE REVIEW

**Review by JADGardner — CHANGES_REQUESTED** [review]
Just fix that conflicting file and otherwise it looks fine :)

**Review by JADGardner — APPROVED** [review]
Looks Good!

**Comment by JADGardner** [comment]
> Just fix that conflicting file and otherwise it looks fine :)

I've fixed the conflict :)

**Review by cmckirgan — APPROVED** [review]
Needs some refactoring but overall good

**Pull request merged**
