### PR TITLE
Iteration 1 GUI

### PR DESCRIPTION
**Pull request by JADGardner**
### TP003 - Graphical User Interface
**User Stories Complete:** 003, 004
**Authors:** James Gardner and Stijn Marynissen

### CODE REVIEW

**Review by ojhstill — APPROVED** [review]
You're crazy if you think I've got time to review 6,000 lines of code, but I trust you enough that you haven't gone and destroyed our livelihood...

**Comment by JADGardner** [comment]
> You're crazy if you think I've got time to review 6,000 lines of code, but I trust you enough that you haven't gone and destroyed our livelihood...

That trust is definitely misplaced.

**Review by dmb537 — CHANGES_REQUESTED** [review]
Unused Import in SecurityTest (package already includes Security module)
Unused Import ServerTools in ClientHandler
Naming inconsistency - MySqlTest vs MySQL, MySQLFactory. I've had this issue with mine  - github doesnt seem to like de-capitalising file names (possibly just an issue on my downloaded version)

Everything else looks good though

**Review by dmb537 — APPROVED** [review]
Looks good - more of an issue for after merge, but are we going for SQL or Sql program-wide? I think checkstyle wants no more than 2 caps in a row,  but we can change that (if you haven't already)

**Pull request merged**
