### PR TITLE
Video tp007 tp017

### PR DESCRIPTION
**Pull request by cmckirgan**

### CODE REVIEW

**Review by JADGardner — CHANGES_REQUESTED** [review]
For the ViewFactory conflicts, can you just keep everything that's is already on the dev branch?

**Comment by cmckirgan** [comment]
> For the ViewFactory conflicts, can you just keep everything that's is already on the dev branch?#

Done

**Review by JADGardner — APPROVED** [review]
🥇 👍

**Review by ojhstill — APPROVED** [review]
YES BOI

**Pull request merged**
