### PR TITLE
Iteration 2 Whiteboard

### PR DESCRIPTION
**Pull request by ojhstill**
TP011 - Interactive Whiteboard

User Stories Complete: n/a
Authors: Oliver Still and Cameron Smith

### CODE REVIEW

**Comment by ojhstill** [comment]
Setup the WhiteboardHandler on the server side to handle the WhiteboardSession packages that are sent across but other than that, the handler isn't finished.

**Review by dmb537 — CHANGES_REQUESTED** [review]
Breaks StreamWindowController (either add constructor without an ID or add ID to StreamWindowController call) - is this something for programmers to fix or for Eric and I to fix as part of Integration?
WhiteboardService, WhiteboardSession and WhiteboardWindowController have checkstyle errors
Lots of random ".DS_Store" - seems to be a Mac thing from Googling - probably want to add that to .gitignore and refresh the branch to remove those

**Comment by ojhstill** [comment]
> Breaks StreamWindowController (either add constructor without an ID or add ID to StreamWindowController call) - is this something for programmers to fix or for Eric and I to fix as part of Integration?

We didn't have access to this controller during this iteration, thus were unaware. This might be something for you guys or a bug for us to fix in the future.

> WhiteboardService, WhiteboardSession and WhiteboardWindowController have checkstyle errors

I'll get on them now.

> Lots of random ".DS_Store" - seems to be a Mac thing from Googling - probably want to add that to .gitignore and refresh the branch to remove those

I do have them in my global gitignore but they've crept back in somehow. I'll remove them.

**Review by JADGardner — APPROVED** [review]
Looks good to me!

**Comment by JADGardner** [comment]
> > Breaks StreamWindowController (either add constructor without an ID or add ID to StreamWindowController call) - is this something for programmers to fix or for Eric and I to fix as part of Integration?
> 
> We didn't have access to this controller during this iteration, thus were unaware. This might be something for you guys or a bug for us to fix in the future.

I think it would be easiest if Dan and Eric just add the extra argument to the Constructor call before testing.

**Review by dmb537 — APPROVED** [review]
Looks good

**Pull request merged**
